config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    resources :recipes, only: [:index, :show]
  end

  root 'users#index', as: :users

  patch 'users/:id' => 'users#update'
  patch 'recipes/:id' => 'recipes#update'

  get '/users' => 'users#index'
  get 'users/new' => 'users#new', as: :new_user
  get 'users/:id' => 'users#show', as: :user
  get 'users/:id/edit' => 'users#edit', as: :edit_user

  get 'sessions/new' => 'sessions#new', as: :new_session
  get 'sessions/destroy' => 'sessions#destroy', as: :destroy_session

  get 'targets/' => 'targets#index', as: :targets

  get 'restaurants/new' => 'restaurants#new', as: :new_restaurant
  get 'restaurants/' => 'restaurants#index', as: :restaurants
  get 'restaurants/:id' => 'restaurants#show', as: :restaurant

  get 'recipes/' => 'recipes#index', as: :recipes
  get 'recipes/new' => 'recipes#new', as: :new_recipe
  get 'recipes/:id' => 'recipes#show', as: :recipe
  get 'recipes/:id/edit' => 'recipes#edit', as: :edit_recipe

  get 'comments/' => 'comments#index', as: :comments

  post 'sessions/new' => 'sessions#create', as: :create_session
  post '/' => 'users#create', as: :create_user
  post 'restaurants/' => 'restaurants#create'
  post 'recipes/' => 'recipes#create'
  post 'comments/' => 'comments#create'
  post 'recipes/:id/likes/' => 'recipes#like', as: :like_recipe

  delete 'recipes/:id' => 'recipes#destroy'
  delete 'comments/:id' => 'comments#destroy', as: :comment_recipe
  delete 'users/:id' => 'users#destroy', as: :delete_user
  delete 'recipes/:id/likes/' => 'recipes#unlike', as: :unlike_recipe

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user
  belongs_to :restaurant
  has_many :comments, :dependent => :destroy
  has_many :likes, :dependent => :destroy

  validates_presence_of :title
  validates_presence_of :restaurant_id
  validates_presence_of :body
end

app/controllers/api/recipes_controller.rb
module Api
  class RecipesController < ApplicationController

      def index
        render json: Recipe.all
      end

      def show
        render json: Recipe.find(params[:id])
      end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @user = User.new
    @recipes = Recipe.all

    if params[:query]

      query = params[:query]
      recipe_list = Recipe.all
      @recipes = []

      recipe_list.each do |recipe|
        if params[:search] == "title"
          search_field = params[:search].to_sym
          if recipe[search_field].downcase.include? query.downcase
            @recipes << recipe
          end
        elsif params[:search] == "restaurant"
          if recipe.restaurant.name.downcase.include? query.downcase
            @recipes << recipe
          end
        end
      end

      return @recipes
    end

  end

  def show
    @recipe = Recipe.find(params[:id])
    @user = User.new
    @comment = Comment.new(:recipe => @recipe)
    @valid = false

    if current_user
      @recipe.likes.each do |like|
        if like.user_id == current_user.id
          @valid = true
        end
      end
    end

  end

  def edit
    @recipe = Recipe.find(params[:id])
    @restaurants = Restaurant.all
    @user = User.new

    if !current_user
      flash[:error] = "You must be signed in to edit a recipe."
      redirect_to recipe_path(@recipe)
    elsif current_user.id != @recipe.user_id
      flash[:error] = "You are not authorized to edit other users' recipes."
      redirect_to recipe_path(@recipe)
    end
  end

  def update
    @recipe = Recipe.find(params[:id])

    if @recipe.update_attributes(recipe_params)
      redirect_to recipe_path(@recipe)
    else
      render :edit
    end
  end

  def new
    @recipe = Recipe.new
    @restaurants = Restaurant.all
    @user = User.new

    if !current_user
      flash[:error] = "You must be signed in to add a recipe."
      redirect_to recipes_path
    else
      @user_id = current_user.id
    end

  end

  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      flash[:success] = "You have added a new recipe."
      redirect_to recipe_path(@recipe)
    else
      flash[:error] = "Your recipe could not be added."
      redirect_to new_recipe_path
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])

    if current_user.id == @recipe.user_id
      if @recipe.destroy
        flash[:success] = "You have deleted a recipe."
        redirect_to recipes_path
      end
    else
      flash[:error] = "You cannot delete another user's recipe."
      redirect_to recipe_path(@recipe)
    end
  end

  def like
    @recipe = Recipe.find(params[:id])

    @recipe.likes.create(user_id: current_user.id)
    redirect_to recipe_path(@recipe)
  end

  def unlike
    @recipe = Recipe.find(params[:id])

    @recipe.likes.where(user_id: current_user.id).each { |like| like.destroy }
    redirect_to recipe_path(@recipe)
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :body, :restaurant_id, :user_id)
  end

end

app/views/recipes/_comment.html.erb
<center><div class="comment">
  <div class="background-style">
    <strong><%=h comment.user.name %> says:</strong>
    <br>
    <%= simple_format h(comment.comment) %>
    <%= link_to 'Delete Comment', [comment, @recipe],
      :method => :delete if current_user %>
  </div>
</div></center>
<br>

app/views/recipes/edit.html.erb
<div class="container">
  <div class="spacer">
    <div class="background-style">
      <div class="padding">
        <br>
        <h3>Edit Your Recipe:</h3>
        <br>

        <%= form_for @recipe do |f| %>

          <div>
            <%= f.label :title, class: 'control-label' %>
            <center><%= f.text_field :title, class: 'form-control' %></center>
          </div>
            <br>
          <div>
            <%= f.label :body, "Recipe Ingredients & Directions", class: 'control-label' %>
            <center><%= f.text_area :body, class: 'form-control', id: 'recipe-form' %></center>
          </div>
            <br>
          <div>
            <%= f.label :restaurant_id, "Restaurant", class: 'control-label' %>
            <center><%= f.select(:restaurant_id, options_for_select(@restaurants.collect{ |restaurant| [restaurant.name, restaurant.id] }.sort)) %></center>
          </div>
            <br>
            <%= f.submit "Update Your Recipe", class: 'btn btn-danger' %>
            <br>
            <br>

        <% end %>
      </div>
    </div>
    <br>
    <br>
    <br>
  </div>
</div>

app/views/recipes/index.html.erb
<div class="container">
  <div class="spacer">
    <div class="centers">
      <%= button_to "Add a New Recipe", new_recipe_path, :method => :get, class: 'btn btn-danger btn-md' %>
        <br>
        <br>
        <div class="background-style">
          <table class="table table-striped">
            <tr>
              <th class="col-md-4">Recipe</th>
              <th class="col-md-3">Restaurant</th>
              <th class="col-md-3">Restaurant Location</th>
              <th class="col-md-1">Likes</th>
              <th class="col-md-1">Comments</th>
            </tr>
          <% @recipes.each do |recipe| %>
            <tr>
              <td><%= link_to recipe.title, recipe_path(recipe) %></td>
              <td><%= recipe.restaurant.name %></td>
              <td><%= recipe.restaurant.location %></td>
              <td><%= recipe.likes.length %></td>
              <td><%= recipe.comments.length %></td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="container">
  <div class="spacer">
    <div class="background-style">
      <div class="padding">
        <br>
          <h3>Add A New Recipe:</h3>
        <br>

        <%= form_for @recipe do |f| %>

          <div>
            <%= f.label :title, class: 'control-label' %>
            <center><%= f.text_field :title, class: 'form-control' %></center>
          </div>
            <br>
          <div>
            <%= f.label :body, "Recipe Ingredients & Directions", class: 'control-label' %>
            <center><%= f.text_area :body, class: 'form-control', id: 'recipe-form' %></center>
          </div>
            <br>
          <div>
            <%= f.label :restaurant_id, "Restaurant", class: 'control-label' %>
            <center><%= f.select(:restaurant_id, options_for_select(@restaurants.collect{ |restaurant| [restaurant.name, restaurant.id] }.sort)) %></center>
          </div>
            <%= f.hidden_field :user_id, :value => current_user.id %>
            <br>
            <%= f.submit "Create Your Recipe", class: 'btn btn-danger' %>
            <br>
            <br>

        <% end %>
     </div>
    </div>
    <br>
    <br>
    <br>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="container">
  <div class="spacer">
    <div class="background-style">
      <div class="padding">
        <br>
          <h3><%= @recipe.title %></h3>
            Submitted by <%= @recipe.user.name %>
            <br>
            <% if current_user %>

                <%= link_to "Edit Recipe", edit_recipe_path %> |
                <%= link_to "Delete Recipe", recipe_path, method: :delete %> |

            <% end %>

                [<%= pluralize(@recipe.likes.count, "like") %>]

            <% if current_user %>

              <% if !@valid %>

                  <%= button_to "Like", like_recipe_path, method: :post, class: 'btn btn-danger btn-xs' %>

              <% else %>

                  <%= button_to "Unlike", unlike_recipe_path, method: :delete, class: 'btn btn-danger btn-xs' %>

              <% end %>

            <% end %>
            <br>
            <br>
              <div style="white-space: pre-wrap;"><%= @recipe.body %></div>
            <br>
              <%= link_to "Back to Restaurant", restaurant_path(@recipe.restaurant_id) %> |
              <%= link_to "Recipes List", recipes_path %>
              <br>
              <% if current_user %>
              <br>
              <%= form_for @comment do |f| %>
                <div>
                <%= f.label :comment, class: 'control-label' %>
                <center><%= f.text_area :comment, class: 'form-control', id: 'comment-form' %></center>
                </div>
                <%= f.hidden_field :recipe_id, :value => @recipe.id %>
                <%= f.hidden_field :user_id, :value => current_user.id %>
                <br>
                <%= f.submit "Submit", class: 'btn btn-danger' %>
                <% end %>

              <% end %>
            <br>
            <br>
            <br>
      </div>
    </div>
      <br>
      <span class="white-text"><%= pluralize(@recipe.comments.length, "Comment") %>:</span>
      <br>
      <br>
      <%= render :partial => 'comment', :collection => @recipe.comments %>
  </div>
</div>