config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    resources :recipes, only: [:index, :show]
  end

  root 'users#index', as: :users

  patch 'users/:id' => 'users#update'
  patch 'recipes/:id' => 'recipes#update'

  get '/users' => 'users#index'
  get 'users/new' => 'users#new', as: :new_user
  get 'users/:id' => 'users#show', as: :user
  get 'users/:id/edit' => 'users#edit', as: :edit_user

  get 'sessions/new' => 'sessions#new', as: :new_session
  get 'sessions/destroy' => 'sessions#destroy', as: :destroy_session

  get 'targets/' => 'targets#index', as: :targets

  get 'restaurants/new' => 'restaurants#new', as: :new_restaurant
  get 'restaurants/' => 'restaurants#index', as: :restaurants
  get 'restaurants/:id' => 'restaurants#show', as: :restaurant

  get 'recipes/' => 'recipes#index', as: :recipes
  get 'recipes/new' => 'recipes#new', as: :new_recipe
  get 'recipes/:id' => 'recipes#show', as: :recipe
  get 'recipes/:id/edit' => 'recipes#edit', as: :edit_recipe

  get 'comments/' => 'comments#index', as: :comments

  post 'sessions/new' => 'sessions#create', as: :create_session
  post '/' => 'users#create', as: :create_user
  post 'restaurants/' => 'restaurants#create'
  post 'recipes/' => 'recipes#create'
  post 'comments/' => 'comments#create'
  post 'recipes/:id/likes/' => 'recipes#like', as: :like_recipe

  delete 'recipes/:id' => 'recipes#destroy'
  delete 'comments/:id' => 'comments#destroy', as: :comment_recipe
  delete 'users/:id' => 'users#destroy', as: :delete_user
  delete 'recipes/:id/likes/' => 'recipes#unlike', as: :unlike_recipe

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :recipes, :dependent => :destroy
  has_many :likes, :dependent => :destroy
  has_many :comments, :dependent => :destroy

  has_secure_password

  validates :email, presence: true, uniqueness: {case_sensitive: false}
  validates_presence_of :name
  validates_presence_of :password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.new
    @users = User.all
  end

  def show
    @user = User.find(params[:id])

    if @user.id != current_user.id
      flash[:error] = "You do not have access to other users' private information."
      redirect_to users_path
    end
  end

  def edit
    @user = User.find(params[:id])

    if @user.id != current_user.id
      flash[:error] = "You are not authorized to edit this user's info."
      redirect_to user_path(@user)
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to user_path(@user)
    else
      flash[:error] = "Please complete the required fields with correct information."
      redirect_to edit_user_path(@user)
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "You have created an account."
      redirect_to users_path
    else
      flash[:error] = "Your account could not be created. Please try again."
      redirect_to new_user_path
    end
  end

  def destroy
    @user = User.find(params[:id])

    if current_user.id == @user.id
      if @user.destroy
        flash[:success] = "Your account has been deleted."
        redirect_to destroy_session_path
      end
    end


  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_pic_url, :email, :password, :password_confirmation)
  end



end

app/views/users/edit.html.erb
<div class="container">
  <div class="spacer">
    <div class="background-style">
      <div class="padding">
        <br>
        <h3>Edit User Info:</h3>
          <h6>* = required</h6>
        <br>

        <%= form_for @user do |f| %>

          <div>
            <%= f.label :name, class: 'control-label' %>*
            <%= f.text_field :name, class: 'form-control' %>
          </div>
            <br>
          <div>
            <%= f.label :profile_pic_url, "Profile Pic URL", class: 'control-label' %>
            <%= f.text_field :profile_pic_url, class: 'form-control' %>
          </div>
            <br>
          <div>
            <%= f.label :email, class: 'control-label' %>*
            <%= f.email_field :email, class: 'form-control' %>
          </div>
            <br>
          <div>
            <%= f.label :password, class: 'control-label' %>*
            <%= f.password_field :password, class: 'form-control' %>
          </div>
            <br>
          <div>
            <%= f.label :password_confirmation, "Password Confirmation", class: 'control-label' %>*
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
            <br>
            <%= f.submit "Update Your Profile", class: 'btn btn-danger' %>
          <br>
          <br>
    <% end %>
      </div>
    </div>
    <br>
    <br>
    <br>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="spacer">
    <div class="black-opaque-background">
      <span class="white-text"><h3>Welcome To RecipeIt!</h3>
      <p>Craving that Chicken & Rice Plate from that restaurant a few thousand miles away? You may not be able to go out and purchase it whenever you want, but RecipeIt can help you replicate that dish with an extensive database of user-contributed recipes of popular restaurant menu items. What recipe will you uncover today?</p></span>
        <br>
    </div>
      <br>
      <br>
      <br>
      <center>
        <div class="black-opaque-background-2">
          <span class="white-text"><h4>Browse:</h4></span>
          <span class="white-link"><%= link_to "Restaurants List", restaurants_path %></span>
            <br>
          <span class="white-link"><%= link_to "Recipes List", recipes_path %></span>
            <br>
            <br>
            <br>
        </div>
      </center>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="spacer">
    <div class="background-style">
      <div class="padding">
      <br>
        <h3>Account Summary</h3>
          <% if @user.profile_pic_url != "" %>
            <%= image_tag @user.profile_pic_url, class: 'profile-pic' %>
          <% else %>
            <%= image_tag ("default_image.png"), class: 'profile-pic' %>
          <% end %>
            <br>
            <br>
          <div><%= @user.name %> | <%= @user.email %></div>
          <br>
          <div># Of Recipes Posted: <%= @user.recipes.length %>
            <br>
              <%= select_tag "search", options_from_collection_for_select(@user.recipes, 'id', 'title') %>
              <br>
              <br>
          </div>

    <div><%= link_to "Edit User Info", edit_user_path %></div>
    <div><%= link_to "Delete Account", delete_user_path(@user), :data => {:confirm => "Are you sure?"}, method: :delete %></div>
        <br>
        <br>
      </div>
    </div>
  </div>
</div>
<br>
<br>