config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    resources :recipes, only: [:index, :show]
  end

  root 'users#index', as: :users

  patch 'users/:id' => 'users#update'
  patch 'recipes/:id' => 'recipes#update'

  get '/users' => 'users#index'
  get 'users/new' => 'users#new', as: :new_user
  get 'users/:id' => 'users#show', as: :user
  get 'users/:id/edit' => 'users#edit', as: :edit_user

  get 'sessions/new' => 'sessions#new', as: :new_session
  get 'sessions/destroy' => 'sessions#destroy', as: :destroy_session

  get 'targets/' => 'targets#index', as: :targets

  get 'restaurants/new' => 'restaurants#new', as: :new_restaurant
  get 'restaurants/' => 'restaurants#index', as: :restaurants
  get 'restaurants/:id' => 'restaurants#show', as: :restaurant

  get 'recipes/' => 'recipes#index', as: :recipes
  get 'recipes/new' => 'recipes#new', as: :new_recipe
  get 'recipes/:id' => 'recipes#show', as: :recipe
  get 'recipes/:id/edit' => 'recipes#edit', as: :edit_recipe

  get 'comments/' => 'comments#index', as: :comments

  post 'sessions/new' => 'sessions#create', as: :create_session
  post '/' => 'users#create', as: :create_user
  post 'restaurants/' => 'restaurants#create'
  post 'recipes/' => 'recipes#create'
  post 'comments/' => 'comments#create'
  post 'recipes/:id/likes/' => 'recipes#like', as: :like_recipe

  delete 'recipes/:id' => 'recipes#destroy'
  delete 'comments/:id' => 'comments#destroy', as: :comment_recipe
  delete 'users/:id' => 'users#destroy', as: :delete_user
  delete 'recipes/:id/likes/' => 'recipes#unlike', as: :unlike_recipe

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :recipes

  validates_presence_of :name
  validates_presence_of :location
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
    @user = User.new
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @restaurants = Restaurant.all
    @user = User.new
    @recipes = Recipe.where(:restaurant_id => @restaurant.id)
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
  end

  def new
    @restaurant = Restaurant.new
    @user = User.new

    if !current_user
      flash[:error] = "You must be signed in to add a restaurant."
      redirect_to restaurants_path
    end
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurants = Restaurant.all
    @user = User.new

    @restaurants.each do |restaurant|
      if restaurant.name == @restaurant.name && restaurant.location == @restaurant.location
        flash[:error] = "This restaurant already exists in the database."
        redirect_to restaurants_path and return
      end
    end

    if @restaurant.save
      flash[:success] = "You have added a new restaurant."
      return redirect_to restaurant_path(@restaurant)
    else
      flash[:error] = "Your restaurant could not be added."
      return redirect_to new_restaurant_path
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :location)
  end
end

app/views/restaurants/index.html.erb
<div class="container">
  <div class="spacer">
    <div class="centers">
      <% if current_user %>
        <%= button_to "Add New Restaurant", new_restaurant_path, :method => :get, class: 'btn btn-danger btn-md' %>
      <% end %>
      <br>
      <br>
      <center><div class="background-style" id="restaurant-table">
        <table class="table table-striped" id="restaurant-table">
          <tr>
            <th class="col-xs-5">Restaurant</th>
            <th class="col-xs-5">Location</th>
            <th class="col-xs-2">Recipes</th>
          </tr>
          <% @restaurants.each do |restaurant| %>
          <tr>
            <td><%= link_to restaurant.name, restaurant_path(restaurant) %></td>
            <td><%= restaurant.location %></td>
            <td><%= restaurant.recipes.length %></td>
          </tr>
          <% end %>
        </table>
      </div></center>
    </div>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <div class="spacer">
    <div class="background-style">
      <div class="padding">
      <br>
        <h3>Add A New Restaurant:</h3>
      <br>

      <%= form_for @restaurant do |f| %>

      <div>
        <%= f.label :name, class: 'control-label' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
        <br>
      <div>
        <%= f.label :location, "City, State", class: 'control-label' %>
        <center><%= f.text_field :location, class: 'form-control', id: 'restaurant-location' %></center>
      </div>
        <br>
        <%= f.submit "Submit New Restaurant", class: 'btn btn-danger' %>
        <br>
        <br>

      <% end %>

      <%= link_to "Back to Restaurant List", restaurants_path %>
        <br>
      </div>
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="spacer">
    <div class="background-style">
      <div class="padding">
        <br>
          <h3><%= @restaurant.name %></h3>
          <h4>[<%= pluralize(@restaurant.recipes.length, "Recipe") %>]</h5>

          <% @recipes.each do |recipe| %>
          <div><%= link_to recipe.title, recipe_path(recipe) %>, Submitted by <%= recipe.user.name %> </div>
          <% end %>

        <br>
        <br>

        <div>
          <%= link_to "Back to Restaurant List", restaurants_path %> |
          <%= link_to "Recipes List", recipes_path %>
        <br>
        <br>
        </div>
      </div>
    </div>
  </div>
</div>