config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    resources :recipes, only: [:index, :show]
  end

  root 'users#index', as: :users

  patch 'users/:id' => 'users#update'
  patch 'recipes/:id' => 'recipes#update'

  get '/users' => 'users#index'
  get 'users/new' => 'users#new', as: :new_user
  get 'users/:id' => 'users#show', as: :user
  get 'users/:id/edit' => 'users#edit', as: :edit_user

  get 'sessions/new' => 'sessions#new', as: :new_session
  get 'sessions/destroy' => 'sessions#destroy', as: :destroy_session

  get 'targets/' => 'targets#index', as: :targets

  get 'restaurants/new' => 'restaurants#new', as: :new_restaurant
  get 'restaurants/' => 'restaurants#index', as: :restaurants
  get 'restaurants/:id' => 'restaurants#show', as: :restaurant

  get 'recipes/' => 'recipes#index', as: :recipes
  get 'recipes/new' => 'recipes#new', as: :new_recipe
  get 'recipes/:id' => 'recipes#show', as: :recipe
  get 'recipes/:id/edit' => 'recipes#edit', as: :edit_recipe

  get 'comments/' => 'comments#index', as: :comments

  post 'sessions/new' => 'sessions#create', as: :create_session
  post '/' => 'users#create', as: :create_user
  post 'restaurants/' => 'restaurants#create'
  post 'recipes/' => 'recipes#create'
  post 'comments/' => 'comments#create'
  post 'recipes/:id/likes/' => 'recipes#like', as: :like_recipe

  delete 'recipes/:id' => 'recipes#destroy'
  delete 'comments/:id' => 'comments#destroy', as: :comment_recipe
  delete 'users/:id' => 'users#destroy', as: :delete_user
  delete 'recipes/:id/likes/' => 'recipes#unlike', as: :unlike_recipe

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecipeIt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>



<header>
<div class="container">
    <h1 id="main-header">RecipeIt</h1>


    <div id="search-bar">
      <%= form_tag('/recipes', method:"get") do %>
      <span class="red-font">Search By</span>
      <%= select_tag "search", options_for_select([["Restaurant", "restaurant"], ["Recipe", "title"]]) %>
      <%= text_field_tag :query %>
      <%= submit_tag "Search", class: 'btn btn-danger btn-sm' %>
      <% end %>
    </div>


    <div id="user-header">

      <span id="alert">
      <% flash.each do |key,value| %>
          <div class="<%= key %>" > <%= value %></div>
      <% end %>
      </span>

      <% if !current_user %>

        <div class="user-header"><%= link_to "Home", users_path %></div> |
        <div class="user-header"><a href="#" data-toggle="modal" data-target="#myModal">Login</a></div> |
        <div class="user-header"><a href="#" data-toggle="modal" data-target="#otherModal">Create An Account</a></div>

      <% else %>

          <div class="user-header"><%= link_to "Home", users_path %></div> |
          <div class="user-header"><%= link_to "Your Account", user_path(current_user) %></div> |
          <div class="user-header"><%= link_to "Logout", destroy_session_path %></div>
      <% end %>

    </div>
</div>


</header>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <center><h3 class="modal-title" id="myModalLabel">RecipeIt</h3></center>
        </div>
        <div class="modal-body">
           <center><h4>Log in</h4></center>
            <div class="row">
              <div class="col-xs-6 col-xs-offset-3">
                <%= form_for @user, url: create_session_path do |f| %>
                  <%= f.email_field :email, :placeholder => "Email", class: 'form-control' %>
                  <br>
                  <%= f.password_field :password, :placeholder => "Password", class: 'form-control' %>
                  <br>
                  <%= f.submit "Log in", class: "btn btn-warning" %>
                <% end %>
              </div>
            </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

<div class="modal fade" id="otherModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <center><h3 class="modal-title" id="myModalLabel">RecipeIt</h3></center>
        </div>
        <div class="modal-body">
           <center><h4>Create An Account</h4><h6>* = Required</h6></center>
            <div class="row">
              <div class="col-xs-6 col-xs-offset-3">
                <%= form_for @user, url: create_user_path do |f| %>

                  <%= f.text_field :name, :placeholder => "Name*", class: 'form-control' %>
                  <br>

                  <%= f.text_field :profile_pic_url, :value => "", :placeholder => "Profile Pic URL", class: 'form-control' %>
                  <br>

                  <%= f.email_field :email, :placeholder => "Email*", class: 'form-control' %>
                  <br>

                  <%= f.password_field :password, :placeholder => "Password*", class: 'form-control' %>
                  <br>

                  <%= f.password_field :password_confirmation, :placeholder => "Password Confirmation*", class: 'form-control' %>
                  <br>


                  <%= f.submit "Create User", class: "btn btn-warning" %>
                <% end %>
              </div>
            </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>





<%= yield %>


<script type="text/javascript" src="http://code.jquery.com/jquery-1.6.4.min.js"></script>
</body>
</html>